apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/kubernetes-manifests

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          app: online-boutique
    target:
      kind: Deployment